name: hello world

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello, World!
        run: |
          echo "Hello, World!"
          echo date
          echo ls
